### ISSUE TITLE
Download app from playstore

### ISSUE THREAD

**Issue by neoreeves** [MishFdM/MIUI_V7_Italy#127]
It's not possibile to download app from playstore without Wi-Fi. With 3g or 4g connection dosn't works.

**Comment by nfalco79** [comment]
You should remove the download limit (default is 10MB, if I remember correctly) from download application.
Open "Download" app -> "Settings" -> "Authorize data usage" -> "Illimited"

**Comment by neoreeves** [comment]
Thanks... :)
