### ISSUE TITLE
Errore app sicurezza

### ISSUE THREAD

**Issue by neoreeves** [MishFdM/MIUI_V7_Italy#128]
Aprendo Impostazioni --> applicazioni di sistema --> sicurezza. Il telefono da errore.

**Comment by kkk701** [comment]
stesso problema su red mi note 2 :
Aprendo Impostazioni --> applicazioni di sistema --> sicurezza == >> applicazione nn installata

**Comment by ale8530** [comment]
@kkk701 Redmi note 2 non è ancora supportato.

@neoreeves Che rom monti? da dove l'hai installata?

**Comment by neoreeves** [comment]
Ho  redmi note 2 prime. Ho la 5.9.18 Hermes.

**Comment by ale8530** [comment]
Non è da noi supportato al momento.

**Comment by neoreeves** [comment]
Ah ok... Perfetto. Grazie per le risposte. Posso approfittare per un'ultima domanda. Avete intenzione di inserire il doppio tap to wake up?
