### ISSUE TITLE
Mancanza di traduzione in Miui Player (Musica) - 5.10.8 (libra)

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#135]
![miui player](https://cloud.githubusercontent.com/assets/15057642/10407771/e9a5a42c-6eef-11e5-98a0-32c5b19482d2.png)
![miui player 2](https://cloud.githubusercontent.com/assets/15057642/10407772/ebf88528-6eef-11e5-9ca0-1e9a6c7d415f.png)

**Comment by ale8530** [comment]
Nella versione 5.10.22 sarà fissato nelle rom versione miui.it, non supportando ancora questo terminale la versione xiaomi.eu non ha la traduzione aggiornata.

Saluti
ale8530
