### ISSUE TITLE
Bug with automatic record of unknown number

### ISSUE THREAD

**Issue by signorarbitro** [MishFdM/MIUI_V7_Italy#141]
hi! I'm here for let you know that there is a bug with this release when the automatic record of unknown number is active. In this case, the InCallUi force crash while the calling is running and you can't see the dialer or the options on calling (mute-headset-contacts etc..). I sent a lot of times the crash log.
I hope you'll solve this at the next release.
Thanks for your great weekly job.
Davide

**Comment by signorarbitro** [comment]
Miui v7 5.10.22

**Comment by signorarbitro** [comment]
Tutto sto tempo perso a spremersi per scrivere in inglese per poi tornare indietro e scoprire da buon cazzone che era in italiano.
Cmq spero di essere stato chiaro.
Crasha InCallUi mentre ricevo o effettuo una chiamata ad un numero sconosciuto (non in rubrica) avendo tra le opzioni di chiamata, la registrazione automatica dei numeri sconosciuti. Ho sempre avuto questa opzione attiva e funzionava alla grande e adesso invece crasha e dopo vari tentativi, mi sono reso conto che disabilitando questa cosa, non crasha più.
Saluti

**Comment by ale8530** [comment]
Puoi postare gentilmente uno screen della funzione?
Il 29/ott/2015 01:25, "signorarbitro" <notifications@github.com> ha scritto:

**Comment by signorarbitro** [comment]
eccolo..

https://www.dropbox.com/s/a60taoohk1l1e7l/Screenshot_2015-10-29-17-31-32_com.android.phone.png?dl=0

**Comment by ale8530** [comment]
Puoi provare gentilmente mettendo la lingua del sistema inglese se hai lo stesso problema?

**Comment by MishFdM** [comment]
Da seguire sul forum, grazie.
