### ISSUE TITLE
Errata traduzione in Messaggi -> Impostazioni avanzate - 5.10.22

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#144]
In Inglese è riportata la parola retrieve che significa "recuperare", infatti quelle impostazioni gestiscono il recupero automatico e non l'invio (invio automatico) degli mms.

![screenshot_2015-11-01-12-33-25_com android mms](https://cloud.githubusercontent.com/assets/15057642/10868768/d47db91c-8098-11e5-9aef-471102446bff.png)

![screenshot_2015-11-01-11-48-19_com android mms](https://cloud.githubusercontent.com/assets/15057642/10868762/94ec7bee-8098-11e5-845e-b93f157f0685.png)

**Comment by ale8530** [comment]
Fissato
