### ISSUE TITLE
Errore traduzione in Sicurezza > Pulisci - 5.10.22 (libra)

### ISSUE THREAD

**Issue by lillipua** [MishFdM/MIUI_V7_Italy#146]
In Sicurezza > Pulizia: C'è un errore accanto a "File in cache", ""%d" che nella lingua inglese è assente. La traduzione più corretta sarebbe "File di cache" senza nessun simbolo seguente e "Cestino" in "spazzatura" o "file inutili". La dicitura "Pericoloso" è assente nella lingua inglese

![screenshot_com miui cleanmaster_2015-10-19-00-09-20](https://cloud.githubusercontent.com/assets/2117411/10869333/175fd0c6-80ad-11e5-9d17-51950dbbbb8a.png)

![screenshot_com miui cleanmaster_2015-10-19-00-08-51](https://cloud.githubusercontent.com/assets/2117411/10869340/3bfc2a7e-80ad-11e5-90ec-1582cb05e264.png)

**Comment by ale8530** [comment]
Questo è già stato fissato, probabilmente hai xiaomi.eu che non ha i nostri ultimi fix.
