### ISSUE TITLE
Descrizione errata in Sicurezza -> Impostazioni utilizzo dati -> Utilizzo dati quotidiano e notifiche - 5.10.22

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#149]
3g indica uno standard e non tutti i tipi di connessione dati (c'è la 4g per esempio). La traduzione inglese non riporta l'abbreviazione "3g", penso dovrebbe essere corretto perché è fuorviante.

![screenshot_2015-11-02-17-53-16_com miui networkassistant](https://cloud.githubusercontent.com/assets/15057642/10888216/3784069a-818b-11e5-851f-611eef4c8d5c.png)

![screenshot_2015-11-02-17-52-09_com miui networkassistant](https://cloud.githubusercontent.com/assets/15057642/10888221/39d1d9cc-818b-11e5-88eb-a366534adf3d.png)

**Comment by MishFdM** [comment]
Corretto
