### ISSUE TITLE
Descrizione errata in Sicurezza (sezione dati) -> Limita - 5.10.22

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#150]
Nella traduzione inglese è riportato new apps' default settings, infatti quei settaggi vanno a modificare le preferenze delle nuove app installate limitandone l'utilizzo dei dati o del wifi, ma non hanno effetto sulle app già presenti. Dovrebbe essere quindi qualcosa come "Impostazioni predefinite per le nuove app".

![screenshot_2015-11-02-18-05-11_com miui networkassistant](https://cloud.githubusercontent.com/assets/15057642/10888531/0f8170b8-818d-11e5-841f-99a603fd38fe.png)

**Comment by ale8530** [comment]
Chiusa

**Comment by ilmonco** [comment]
Proposto un cambio.
