### ISSUE TITLE
Mancata traduzione di alcune voci in Musica - 5.11.5

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#153]
Ditemi se è un problema di tempistica di invio della traduzione a Xiaomi.eu così non lo segnalo più. (scusate)

![screenshot_2015-11-09-14-50-00_com miui player](https://cloud.githubusercontent.com/assets/15057642/11037238/132737fa-86fd-11e5-95ce-e4c4e3bd3a6d.png)

**Comment by ale8530** [comment]
Chiusa versione italiana è apposto.

**Comment by fantakk** [comment]
Per versione italiana intendi la ROM di miui.it? Perché in quella di Xiaomi.eu c'è.(libra)

**Comment by ale8530** [comment]
Si miui.it, alcuni fix per impossibilità di applicazione non possono essere implementati sulla versione xiaomi.eu

**Comment by fantakk** [comment]
Ho capito, non la segnalo più per le prossime versioni dunque. Grazie.
