### ISSUE TITLE
Traduzione mancante in gestione notifiche - 5.11.5 (Xiaomi.eu)

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#156]
Nell'ultima build sono state separate le funzioni di notifiche in lockscreen e notifica a comparsa.
In gestione notifiche andando su un app c'è come una doppia voce. C'è "Lockscreen" e "Notifiche mobili e Lockscreen".

**Comment by ale8530** [comment]
Puoi postare screenshot gentilmente?

**Comment by fantakk** [comment]
sì, ecco. 

![screenshot_2015-11-11-15-12-54_com android settings](https://cloud.githubusercontent.com/assets/15057642/11092910/2d7a5de0-8887-11e5-870e-0e1d31419dd3.png)
