### ISSUE TITLE
Voci non tradotte in inglese nell'applicazione Musica - 5.11.12 (Xiaomi.eu)

### ISSUE THREAD

**Issue by fantakk** [MishFdM/MIUI_V7_Italy#157]

**Comment by MishFdM** [comment]
Non segnalate, ripeto NON SEGNALATE mancate traduzioni e typo delle versioni Xiaomi.eu, solo versioni Miui.it. Grazie.

**Comment by ilmonco** [comment]
Ciao, @MishFdM . quindi non si può fare nulla per la traduzione dell'app Musica nella versione xiaomi.eu?
