### ISSUE TITLE
Mancata traduzione quando si disinstalla un'app - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#159]
Quando si disinstalla un'app il messaggio di avviso non è tradotto

![screenshot_2015-11-24-23-20-54_com android packageinstaller](https://cloud.githubusercontent.com/assets/16007271/11382473/5379d5e0-9302-11e5-880b-146f341a47bc.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato prossima release.
