### ISSUE TITLE
Mancata traduzione in Sicurezza - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#160]
"Battery" non è tradotto 

![2015-11-24 23 26 11](https://cloud.githubusercontent.com/assets/16007271/11382554/daefbf1c-9302-11e5-9cfc-51d248eeb3ee.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato prossima release.
