### ISSUE TITLE
Errore traduzione in Browser - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#161]
In Browser, accanto a Segnalibri c'e uno / assente nella versione inglese

![2015-11-24 23 27 50](https://cloud.githubusercontent.com/assets/16007271/11382643/612322f4-9303-11e5-8c65-72053d7c0067.png)

![screenshot_2015-11-24-23-31-15_com android browser](https://cloud.githubusercontent.com/assets/16007271/11382700/9cedd2c0-9303-11e5-8dce-49177b5c3736.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato per prossima release, abbiamo ridotto le parole purtroppo per questioni di spazio non entra.

**Comment by timaniac00** [comment]
Capito, grazie
