### ISSUE TITLE
Errore traduzione in Sicurezza > Batteria - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#162]
In Sicurezza - Batteria c'è un errore di traduzione. La dicitura corretta dovrebbe essere "Carica completata tra 28 minuti"

![screenshot_2015-11-24-23-34-09_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/11382776/26343b14-9304-11e5-951a-3952602bdeda.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato per prossima release.

**Comment by MarkH-UK** [comment]
unsub me from this noise please.

On 25 November 2015 at 16:53, ale8530 <notifications@github.com> wrote:

> Closed #162 <https://github.com/MishFdM/MIUI_V7_Italy/issues/162>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MishFdM/MIUI_V7_Italy/issues/162#event-474251666>.
>



-- 
Mark Hedley

*Developer | IT | Android | Servers | Networks | SEO*
