### ISSUE TITLE
Errore traduzione in Sicurezza - Permessi - Avvio automatico 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#163]
In Sicurezza - Permessi - Avvio automatico il testo in alto dovrebbe essere corretto in "XX app non possono autoavviarsi" oppure "A XX app non è consentito autoavviarsi"

![screenshot_2015-11-24-23-46-04_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/11383106/4293389e-9306-11e5-9a56-6de33090bcf4.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato per prossima release.
