### ISSUE TITLE
Mancata traduzione in Impostazioni - Informazioni sul dispositivo - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#164]
In Impostazioni - Informazioni sul dispositivo - "Android security patch level" non è tradotto in "Livello patch di sicurezza Android" come indicato nella traduzione ufficiale di Google 
https://support.google.com/nexus/answer/4457705?hl=it

![2015-11-24 23 54 06](https://cloud.githubusercontent.com/assets/16007271/11383173/b8043808-9306-11e5-805c-490bd0d3b4da.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato per prossima release.
