### ISSUE TITLE
Mancata traduzione in Impostazioni - Impostazioni aggiuntive - Memoria 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#165]
Mancata traduzione in Impostazioni - Impostazioni aggiuntive - Memoria: "Mount USB storage..."

![2015-11-24 23 55 58](https://cloud.githubusercontent.com/assets/16007271/11383240/2a7f0d7c-9307-11e5-833c-ef80911aba84.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato per prossima release
