### ISSUE TITLE
Errore traduzione in Impostazioni - Impostazioni aggiuntive - Batteria - Consumo batteria - Dettagli cronologia - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#166]
Errore traduzione in Impostazioni - Impostazioni aggiuntive - Batteria - Consumo batteria - Dettagli cronologia: "xxm xxs su batteria" andrebbe sostituito con "xxm xxs con la batteria" e il titolo "Dettagli cronologia" con "Dettagli utilizzo batteria"

![2015-11-25 00 00 35](https://cloud.githubusercontent.com/assets/16007271/11383430/63709e9c-9308-11e5-9913-aade0d0cead0.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato prossima release.
