### ISSUE TITLE
Mancata traduzione nella notifica di chiamata persa 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#167]
La notifica di chiamata persa non è tradotta in italiano

![screenshot_2015-11-25-00-57-02_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/16007271/11384468/5a4ed06a-9310-11e5-8312-a95ff423a0d5.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato per prossima release.

**Comment by MarkH-UK** [comment]
mish, dude... take me off this repo please.

On 25 November 2015 at 17:13, ale8530 <notifications@github.com> wrote:

> Fissato per prossima release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MishFdM/MIUI_V7_Italy/issues/167#issuecomment-159544072>
> .
>



-- 
Mark Hedley

*Developer | IT | Android | Servers | Networks | SEO*
