### ISSUE TITLE
Errore traduzione in Browser 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#168]
Nel Browser, Banda/Attivata e Banda/Disattivata andrebbe sostituito con "Risparmio dati" in entrambi i casi come avviene nelle traduzione inglese

![screenshot_2015-11-25-13-47-23_com android browser](https://cloud.githubusercontent.com/assets/16007271/11397649/4bc4b684-937b-11e5-9e6b-5c83a37ce254.png)
![screenshot_2015-11-25-13-45-17_com android browser](https://cloud.githubusercontent.com/assets/16007271/11397651/4f53cae2-937b-11e5-8946-092ca24ff778.png)
![screenshot_2015-11-25-13-45-47_com android browser](https://cloud.githubusercontent.com/assets/16007271/11397657/52ddda0e-937b-11e5-89ff-58ee2ab44575.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by SkiFire13** [comment]
Risparmio Dati/Attivato non è forse un po' troppo lungo?

**Comment by timaniac00** [comment]
Intendevo dire "Risparmio dati" senza Attivato o Disattivato così come avviene nella traduzione inglese. L'attivazione dell'opzione è indicata giù dal colore arancione del testo e la disattivazione invece da quello nero

**Comment by SkiFire13** [comment]
Ho provato a proporre il cambiamento sotto forma di pull request (insieme ad altre traduzioni per la 5.11.25)

**Comment by ale8530** [comment]
La giusta frase è "Risparmio dati"

**Comment by ale8530** [comment]
Chiusa
