### ISSUE TITLE
Mancata traduzione in Impostazioni - Notifiche - Gestisci notifiche - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#170]
Manca la traduzione in italiano in Impostazioni - Notifiche - Gestisci notifiche e cliccando su un'app

![screenshot_2015-11-26-04-45-44_com android settings](https://cloud.githubusercontent.com/assets/16007271/11414711/e44f27f4-93f8-11e5-9349-075800ec23cc.png)

![screenshot_2015-11-25-22-53-41_com android settings](https://cloud.githubusercontent.com/assets/16007271/11411693/ddcaa5fa-93d2-11e5-8ec5-810a090d0c47.png)

![screenshot_2015-11-26-00-16-21_com android settings](https://cloud.githubusercontent.com/assets/16007271/11411703/14897af8-93d3-11e5-98ad-e46012c28a5c.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by fantakk** [comment]
Confermo

**Comment by SkiFire13** [comment]
Fixato nel mio pool. Il file è in main/Settings.apk/res/values-it/plurals.xml

**Comment by ale8530** [comment]
Fissato prossima release.
