### ISSUE TITLE
Errore di traduzione in Impostazioni - Modalità Genitore - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#171]
In Impostazioni - Modalità Genitore c'è un errore di battitura "tocc ail tasto Home..."

![screenshot_2015-11-25-22-59-19_com android settings](https://cloud.githubusercontent.com/assets/16007271/11411725/6ecda23c-93d3-11e5-9602-1795a3f6f149.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by SkiFire13** [comment]
Fixato nel mio pull. File da modificare main / device / (libra|leo|hermes|ferrari) / Settings.apk / res / values-it / strings.xml (righe 3671-3672)

**Comment by ale8530** [comment]
Fissato per prossima release.
