### ISSUE TITLE
Mancata traduzione in Impostazioni  - Anti-disturbo -  5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#172]
Mancata traduzione in Impostazioni - Anti-disturbo: "DO NOT DISTURB"

![screenshot_2015-11-25-22-58-54_com android settings](https://cloud.githubusercontent.com/assets/16007271/11411745/ad013082-93d3-11e5-97c1-d01990a1a594.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by ale8530** [comment]
Fissato prossima release
