### ISSUE TITLE
Mancata traduzione in Sicurezza - Monthy report -  5.11.19 (hermes) 

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#173]
Mancata traduzione in Sicurezza - Monthy report

![screenshot_2015-11-26-00-23-34_com miui securityadd](https://cloud.githubusercontent.com/assets/16007271/11411767/074880cc-93d4-11e5-8fff-ed95b643bc15.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by SkiFire13** [comment]
Fixato nel mio pool. Il file è in main/SecurityAdd.apk/res/values/strings.xml (va creato manualmente).

Per la traduzione in inglese https://github.com/Acid-miuipolskapl/v6-XML-Compare/blob/8044545deb63842e0f5d91b8ba0732bd596a10a4/hermes/SecurityAdd.apk/res/values/strings.xml

**Comment by ilmonco** [comment]
@SkiFire13 fatto pull request?

**Comment by SkiFire13** [comment]
Visto che la repo italiana è stata modificata non è più compatibile...
