### ISSUE TITLE
Mancata traduzione in Sicurezza - Utilizzo dati - Ricarica - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#174]
Mancata traduzione in Sicurezza - Utilizzo dati - Ricarica 

![screenshot_2015-11-26-00-09-41_com miui securityadd](https://cloud.githubusercontent.com/assets/16007271/11411799/8811b5ac-93d4-11e5-93e1-ee7dcca1e8bd.png)

Versione miui 5.11.19 scaricata da miui.it e installata su Xiaomi Redmi Note 2

**Comment by SkiFire13** [comment]
Fixato nel mio pool. Il file è in main/SecurityAdd.apk/res/values/strings.xml (va creato manualmente).

Per la traduzione in inglese https://github.com/Acid-miuipolskapl/v6-XML-Compare/blob/8044545deb63842e0f5d91b8ba0732bd596a10a4/hermes/SecurityAdd.apk/res/values/strings.xml

**Comment by ilmonco** [comment]
@SkiFire13 Fatto Pull Request?
