### ISSUE TITLE
Mancata traduzione quando si riceve un file via bluetooth - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#175]
Mancata traduzione quando si riceve un file via bluetooth

![screenshot_2015-11-26-23-44-56_com android bluetooth](https://cloud.githubusercontent.com/assets/16007271/11431444/4bcf99f0-9498-11e5-9d81-bcc986c3ef0f.png)

questo è quello che viene mostrato quando si imposta la lingua inglese:
![screenshot_2015-11-26-23-42-28_com android bluetooth](https://cloud.githubusercontent.com/assets/16007271/11431446/4e144cd8-9498-11e5-9afa-6d45857ddc18.png)

**Comment by ale8530** [comment]
Fissato per prossima release.
