### ISSUE TITLE
Errore traduzione in Calendario - Nuovo evento 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#177]
Errore traduzione in Calendario - Nuovo evento - Ripetizione - Personalizza.

![screenshot_2015-11-27-23-16-21_com android calendar](https://cloud.githubusercontent.com/assets/16007271/11449096/0b491bd6-956a-11e5-87d5-28110fa4f019.png)

**Comment by ale8530** [comment]
é stato già fissato per la relese 5.11.26
