### ISSUE TITLE
Errore traduzione in Radio - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#178]
Errore traduzione in Radio: "Lista registrazione" dovrebbe essere sostituito con "Lista registrazioni", "Aggiungi alle preselezioni" con "Aggiungi ai preferiti", "Sospensione" con "Disattiva"

![screenshot_2015-11-27-23-13-45_com miui fm](https://cloud.githubusercontent.com/assets/16007271/11449108/5c8439d6-956a-11e5-8626-d0d98196f4c3.png)

**Comment by ale8530** [comment]
accettato solo "Lista registrazione" il resto va bene cosi, sarà implementato release prossima settimana.
