### ISSUE TITLE
Mancata traduzione in Impostazioni - Informazioni sul dispositivo - Stato - 5.11.19 (hermes) 

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#179]
Mancata traduzione in Impostazioni - Informazioni sul dispositivo - Stato: "Voice" e "Data"
![cattur6a](https://cloud.githubusercontent.com/assets/16007271/11449163/0bbe5bb0-956c-11e5-9eff-f5b9f309a929.PNG)

**Comment by ale8530** [comment]
Non può essere tradotto mi spiace.
