### ISSUE TITLE
Errore di traduzione in Meteo - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#180]
In Meteo, "Gibbosa calante" andrebbe sostituito con "Luna calante". L' indice UV, dal momento che è una scala, non può essere debole o forte ma alto o basso
![cattur66a](https://cloud.githubusercontent.com/assets/16007271/11449189/8f78c56c-956c-11e5-9580-3456d99319b8.PNG)

**Comment by SkiFire13** [comment]
Gibbosa calante è una fase intermedia delle fasi lunari
https://it.wikipedia.org/wiki/Fasi_lunari#Le_lune

**Comment by ale8530** [comment]
Chiusa va bene già com'è
