### ISSUE TITLE
Errore traduzione in Notifica - Trova dispositivo  - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#183]
C'è un errore di battitura: 

"Accedia..."

"...un messaggioper riattivare..."

![screenshot_2015-11-29-15-24-21_com miui cloudservice](https://cloud.githubusercontent.com/assets/16007271/11457613/b248008e-96ad-11e5-906c-78e8731ca802.png)

Il testo, nonostante sia lo stesso di quello precedente, è tradotto in modo diverso. "cancellare" andrebbe sostituito con "formattare"
![screenshot_2015-11-29-15-31-46_com xiaomi finddevice](https://cloud.githubusercontent.com/assets/16007271/11457641/97389802-96ae-11e5-809f-16824dfa2eed.png)

**Comment by ilmonco** [comment]
Proposta correzione
