### ISSUE TITLE
Errore traduzione in Browser - Impostazioni - Azzera dati -  5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#184]
Errore traduzione in Browser - Impostazioni - Azzera dati.

"Cancellare tutte le password salvate?" andrebbe sostituito con "Cancella tutte le password salvate"

![screenshot_2015-11-29-15-48-09_com android browser](https://cloud.githubusercontent.com/assets/16007271/11457726/eac46044-96b0-11e5-8976-9f1ffb3e3f5b.png)

**Comment by ilmonco** [comment]
Proposta correzione
