### ISSUE TITLE
Errore traduzione in Impostazioni - Applicazioni di sistema - Sicurezza -  5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#185]
Errore traduzione in Impostazioni - Applicazioni di sistema - Sicurezza - Ottimizza in standby: "Tra xx min..." andrebbe sostituito con "Dopo xx min..."

![screenshot_2015-11-29-15-56-03_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/11457773/dfb6b6b0-96b1-11e5-85a6-fb5f92c604a2.png)

**Comment by ilmonco** [comment]
Proposta correzione
