### ISSUE TITLE
Errore traduzione in Impostazioni - Applicazioni di sistema - Video - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#186]
Errore traduzione in Impostazioni - Applicazioni di sistema - Video - Impostazioni di Sviluppo

"Charging to update app.." non è tradotto

Errore di battitura: "...viene visualizzata la modalitaà"

![screenshot_2015-11-29-15-53-55_com miui video](https://cloud.githubusercontent.com/assets/16007271/11457779/2bd41e0c-96b2-11e5-9b20-81876c956620.png)

**Comment by ilmonco** [comment]
Proposta correzione
