### ISSUE TITLE
Errore traduzione in Impostazioni - Applicazioni di sistema - Video - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#187]
Errore traduzione in Impostazioni - Applicazioni - Altro - Reimposta preferenze app.

"notifiche di app disattivate" andrebbe sostituito con "Notifiche app disattivate"

![screenshot_2015-11-29-16-11-35_com android settings](https://cloud.githubusercontent.com/assets/16007271/11457890/305dff94-96b5-11e5-8842-687da8b52a51.png)

**Comment by ilmonco** [comment]
corretto
