### ISSUE TITLE
Errore traduzione in Sicurezza - Pulizia - 5.11.19 (hermes)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#188]
Errore traduzione in Sicurezza - Pulizia: "Cestino" andrebbe sostituito con "spazzatura", "Pericoloso" con "Pulisci l'archiviazione interna", "Pulizia xxGB" con "Pulisci xxGB" o "Elimina XXGB" come nella lingua inglese

![screenshot_2015-11-29-16-26-33_com miui cleanmaster](https://cloud.githubusercontent.com/assets/16007271/11457925/2f6082b4-96b6-11e5-9b40-f74085d4490a.png)

![screenshot_2015-11-29-16-26-00_com miui cleanmaster](https://cloud.githubusercontent.com/assets/16007271/11457931/6dd8b69c-96b6-11e5-91d0-aa6e767c79c3.png)

**Comment by ilmonco** [comment]
proposta correzione.
