### ISSUE TITLE
Refuso in Messaggi - 5.11.26

### ISSUE THREAD

**Issue by ghost** [MishFdM/MIUI_V7_Italy#189]
![screenshot_2015-11-30-19-38-22_com android mms](https://cloud.githubusercontent.com/assets/15057642/11483464/b5d3c732-97a8-11e5-9918-aa4664f2acb6.png)

**Comment by ilmonco** [comment]
Possiamo mettere close?

**Comment by ilmonco** [comment]
Corretto
