### ISSUE TITLE
Inglese in Gestisci notifiche

### ISSUE THREAD

**Issue by hermesx** [MishFdM/MIUI_V7_Italy#295]
![screenshot_2015-12-08-18-36-57_com android settings](https://cloud.githubusercontent.com/assets/16180621/11663357/0fe24fa8-9ddc-11e5-9b02-cc4a5975bcea.png)

HERMES. all'interno è corretto......

**Comment by ilmonco** [comment]
@MishFdM Può essere perché mancano queste 3 stringhe sui settings.apk dei device?  

    <string name="status_bar_app_enable_message">Badges</string>
    <string name="status_bar_app_enable_floating">Floatings notifications</string>
    <string name="status_bar_app_enable_keyguard">Lock screen</string>

**Comment by ilmonco** [comment]
Proposta correzione in #303, #304 , #305 , #306, #307

**Comment by ilmonco** [comment]
Proposta correzione in #300 #303, #323 , #325 , #326, #327  e cancro in #344
