### ISSUE TITLE
Lockscreen e widget orologio non concordano.

### ISSUE THREAD

**Issue by ilmonco** [MishFdM/MIUI_V7_Italy#368]
È possibile farli concordare? Dovrebbe essere tutto in minuscolo seguendo l'italiano. http://www.accademiadellacrusca.it/it/lingua-italiana/consulenza-linguistica/domande-risposte/alcuni-quesiti-nomi-mesi-giorni-settimana

![screenshot_2015-12-09-00-28-53_com miui home](https://cloud.githubusercontent.com/assets/16099943/11671978/8d6c3562-9e0c-11e5-8e1e-39e34f03d327.png)
![screenshot_2015-12-09-00-28-42_com miui home](https://cloud.githubusercontent.com/assets/16099943/11671979/8d6e6634-9e0c-11e5-9095-429cc3b5ca1a.png)

**Comment by ale8530** [comment]
La lockscreen dovrebbe prendere le variabili dal framework-res.apk, che terminale hai?

**Comment by ilmonco** [comment]
Un Mi 4c quindi libra, sì infatti non trovo la stringa interessata

**Comment by ale8530** [comment]
Penso che devono essere modificate le date dentro l'applicazione miui.apk, se viene utilizzata la la frase "mer"  anche "Dicembre" va inserito "dicembre" per dare omogeneità alla UI.

Vediamo cosa dice Mish.
