### ISSUE TITLE
Scritte cinese in funzione di ricerca hermes

### ISSUE THREAD

**Issue by hermesx** [MishFdM/MIUI_V7_Italy#384]
![a76ee552-9517-11e5-8df1-128d530b87b9](https://cloud.githubusercontent.com/assets/16180621/11764481/652eee68-a132-11e5-870d-f1308ba02faa.png)

**Comment by ilmonco** [comment]
Posso solo dire che hanno già detto che la soluzione proposta da @ingbrzy manda in crash e FC l'app Cerca nella versione italiana...

**Comment by MishFdM** [comment]
Per adesso testo cinese o FC. Cmq il problema verrà risloto a breve, chiudo
