### ISSUE TITLE
Loop nuova installazione

### ISSUE THREAD

**Issue by namaless** [MishFdM/MIUI_V7_Italy#410]
Ho notato oggi facendo una nuova installazione della miui v5.12.24 che se parto con la lingua italiana, dopo la selezione di mi-cloud l'applicazione si blocca in modo anomalo. Questo non succede se seleziono la lingua inglese ad'esempio.

**Comment by xazac** [comment]
Questo è un bug della MIUI_eu

**Comment by namaless** [comment]
Perdona l'ignoranza, ma come puo essere un bug della miui_eu che se metto qualsiasi altra lingua procede alla tab miui-voice, mentre il problema fc lo da solo con la lingua italiana?

**Comment by xazac** [comment]
Ciao, perdonami, ma forse sono stato poco chiaro. Il bug del quale parli è presente nella ROM di MIUI_EU e non nella ROM di MIUI.it. Il bug non riguarda la traduzione italiana ma la ROM in sè. Prova ad installare la ROM per il tuo dispositivo scaricandola da miui.it e facci sapere. Grazie!

**Comment by namaless** [comment]
Questo non risolve il problema, e ribadisco se il problema persiste 
unicamente con la lingua italiana credo che sia il caso prima di 
imputare l'errore alla rom (che con le altre lingue funziona 
perfettamente) di cercare di sistemare il problema. Visionando il 
sorgente della lingua con quello del repository ufficiale si puo notare 
la mancanza di una moltitudini di stringhe non inserite, magari potrebbe 
essere questo il problema, non ho idea, do qualche suggerimento. 
Fondamentalmente non mi interessa in quanto posso tranquillamente tenere 
il terminale in lingua inglese.

Il 26/12/2015 21:40, Roberto ha scritto:

**Comment by xazac** [comment]
È strano che tu dica che questo non risolve il problema, ho provato personalmente la 5.12.17 di Xiaomi.eu e il bug è presente e nella 5.12.17 di MIUI.it il bug non si verifica.
Tra le Known issues di Xiaomi.eu è di fatto indicato "- If you have MiCloud FC during initial setup, set your lang to EN. after setup you can switch back to your lang."
La mancanza delle stringhe di fatto non creano problemi, se non appunto la mancata traduzione.
Le critiche vanno fatte a patto di essere costruttive, non serve lamentarsi per il gusto di farlo e non accettare le soluzioni proposte facendo addirittura sparate come il tuo "fondamentalmente non mi interessa".
D'ora in avanti, ti pregherei di accettare i suggerimenti  allo stesso modo di come i tu proponi dei suggerimenti "non avendo idea".
Grazie.

Inviato da iPad Pro
