### ISSUE TITLE
scritte cinesi in hot spot personale

### ISSUE THREAD

**Issue by liberato78** [MishFdM/MIUI_V7_Italy#412]
IMPOSTAZIONI
IMPOSTAZIONI AGGIUNTIVE
HOTSPOT PERSONALE
CONFIGURA HOTSPOT WIFI
SSID RETE " PAROLE IN CINESE"

**Comment by xazac** [comment]
Ciao, posso chiederti il dispositivo sul quale hai riscontrato l'errore? Grazie!

**Comment by liberato78** [comment]
Redmi note 2

**Comment by ale8530** [comment]
Hai ancora il problema? Puoi postare screen?

**Comment by ale8530** [comment]
Chiusa per mancata risposta
