### ISSUE TITLE
testo non allineato in blacklist

### ISSUE THREAD

**Issue by liberato78** [MishFdM/MIUI_V7_Italy#413]
Nella sezione blacklist di sicurezza sotto impostazioni - impostazioni addizionali - il testo non è ben allineato per ogni selezione

**Comment by xazac** [comment]
Ciao, posso chiederti su quale dispositivo hai riscontrato l'errore? Grazie!

**Comment by liberato78** [comment]
Si scusa se non l ho specificato. Redmi note 2 16Gb

**Comment by xazac** [comment]
Grazie mille. Riusciresti ad allegare uno screenshot?

**Comment by liberato78** [comment]
![screenshot_2015-12-27-21-48-58_com miui antispam](https://cloud.githubusercontent.com/assets/16443431/12011942/29542aee-ace4-11e5-9ef2-61a899a4e3c4.png)
![screenshot_2015-12-27-21-48-54_com miui antispam](https://cloud.githubusercontent.com/assets/16443431/12011943/3799331a-ace4-11e5-9be9-8ac952d7da7e.png)
![screenshot_2015-12-27-21-48-47_com miui antispam](https://cloud.githubusercontent.com/assets/16443431/12011945/41f06aea-ace4-11e5-91a8-119b1baa243f.png)

**Comment by liberato78** [comment]
La prima allinea correttamente le altre due no

**Comment by xazac** [comment]
Credo che lì c'entri la dimensione che hai impostato per i caratteri di sistema più che un errore nelle stringhe. A quanto hai impostato la dimensione? (S, M, L, etc.)

**Comment by liberato78** [comment]
I tre screenshot di prima sono a dimensione M

**Comment by liberato78** [comment]
![screenshot_2015-12-27-22-05-42_com miui antispam](https://cloud.githubusercontent.com/assets/16443431/12012003/4bdd6506-ace6-11e5-8082-42a75097abf3.png)
![screenshot_2015-12-27-22-05-36_com miui antispam](https://cloud.githubusercontent.com/assets/16443431/12012005/55d76cfa-ace6-11e5-9e55-9beb25dc8b48.png)
![screenshot_2015-12-27-22-05-29_com miui antispam](https://cloud.githubusercontent.com/assets/16443431/12012006/61730d6c-ace6-11e5-9515-0a9366aeeee5.png)

**Comment by liberato78** [comment]
Queste a dimensione S.

**Comment by xazac** [comment]
Di fatto, nelle stringhe non ci sono errori se non il fatto che la traduzione italiana è troppo lunga. Ho controllato le voci in inglese e le ho modificate come segue:

Notifica elemento bloccato > Notifiche blacklist

Mostra quando una chiamata viene bloccata > Tutte le chiamate

Mostra quando una chiamata non presente nella blacklist viene bloccata > Solo chiamate non in blacklist

Non mostrare notifiche > Mai

Ora la traduzione è più snella e coerente con le voci in lingua originale.
