### ISSUE TITLE
redminote note 2 - email

### ISSUE THREAD

**Issue by liberato78** [MishFdM/MIUI_V7_Italy#417]
nell'app email in impostazioni - account - utilizzo dati -
la voce 'keep for' potrebbe essere tradotta in mantieni per o conserva per

sincronizza opzioni 
potrebbe essere cambiata in sincronizza cartelle 
la didascalia sotto sincronizza opzioni - folder sync settings tradotta opzioni di sincronizzazione o anche nnt visto che gia il titolo principale fa capire di cosa si tratta

rimuovi account
esce la finestra con i motivi da comunicare perche si vuole cancellare l'account da tradurre completamente

sempre in email - impostazioni
sotto generali da tradurre Confirm before sending 

grazie siete grandi

**Comment by xazac** [comment]
Dispositivo? Grazie!

**Comment by liberato78** [comment]
Sta scritto nell'oggetto della segnalazione . cmq redmi note 2

**Comment by liberato78** [comment]
Primi due risolti 
Gli altri due anche con 6.1.7 ancora da risolvere

**Comment by ale8530** [comment]
Quali sono quelli che mancano?

**Comment by ale8530** [comment]
Chiusa per mancata risposta
