### ISSUE TITLE
Calendario stock non suona quando appare un evento registrato 

### ISSUE THREAD

**Issue by angelo1976** [MishFdM/MIUI_V7_Italy#418]
Buongiorno ho notato con la rom 5.12.24 che il calendario di stock non suona quando appare un evento registrato. Esce solo l'avviso ma senza suoneria. Ho provato ad impostare suonerie di default ma non va. Con la versione precedente andava. Grazie

**Comment by liberato78** [comment]
ciao angelo a me notifica col bip la fa

**Comment by angelo1976** [comment]
A me no........ Però io ho un terminale diverso. Che sia quello? Poi magari è un problema della rom di xiaomi.eu e giustamente lo staff di miui.it chiude la segnalazione 



Inviato tramite XiaomiIl liberato78 <notifications@github.com>, 29/dic/2015 10:02 ha scritto:ciao angelo a me notifica col bip la fa

**Comment by liberato78** [comment]
allora specifica qui anche che terminale hai cosi li aiutiamo meglio

**Comment by angelo1976** [comment]
Come si può editare il messaggio? Cmq ho scritto che terminale ho in uno dei tre messaggi 



Inviato tramite XiaomiIl liberato78 <notifications@github.com>, 29/dic/2015 10:12 ha scritto:allora specifica qui anche che terminale hai cosi li aiutiamo meglio
