### ISSUE TITLE
Salvataggio file da browser stock su sd 

### ISSUE THREAD

**Issue by angelo1976** [MishFdM/MIUI_V7_Italy#419]
Buongiorno con la rom 5.12.24 ho notato che sebbene sia impostata la sd per salvare i file scaricati dal browser di stock, vengono salvati sempre nella memoria interna del telefono. 
Le altre applicazioni salvano regolarmente su sd. 
Redmi 2 2gb versione 2014813

**Comment by xazac** [comment]
Segnala questo bug qui: http://en.miui.com/forum.php?mod=bugfeedback&fid=5
Controlla prima se qualcun altro l'ha segnalato, in caso contrario puoi farlo tu!

Grazie

**Comment by angelo1976** [comment]
Ok grazie a te 



Inviato tramite XiaomiIl Roberto <notifications@github.com>, 30/dic/2015 20:16 ha scritto:Segnala questo bug qui: http://en.miui.com/forum.php?mod=bugfeedback&fid=5
Controlla prima se qualcun altro l'ha segnalato, in caso contrario puoi farlo tu!

Grazie
