### ISSUE TITLE
Mancata traduzione in privacy 

### ISSUE THREAD

**Issue by angelo1976** [MishFdM/MIUI_V7_Italy#420]
Buongiorno ho notato che il menù privacy non è completamente tradotto (impostazioni - impostazioni aggiuntive - privacy - privacy setting) ed anche due righe sotto la voce amministrazione dispositivo (

**Comment by liberato78** [comment]
a me sono tutte tradotte a parte la parola privacy che penso possa andar bene anche in italiano

**Comment by xazac** [comment]
Angelo puoi dirmi il dispositivo sul quale hai riscontrato la mancata traduzione? Grazie

**Comment by angelo1976** [comment]
Redmi 2 2014813 o se preferisci redmi 2 2gb td 



Inviato tramite XiaomiIl Roberto <notifications@github.com>, 30/dic/2015 20:14 ha scritto:Angelo puoi dirmi il dispositivo sul quale hai riscontrato la mancata traduzione? Grazie

**Comment by xazac** [comment]
Effettivamente non ho trovato stringhe non tradotte. Prova a fare un wipe!

**Comment by angelo1976** [comment]
Ho fatto sia wipe cache che wipe dallvik. Ti invio due screenshot, uno per privacy uno per amministrazione dispositivo (verify apps)

**Comment by angelo1976** [comment]
ciao ti ho inviato via mail due screenshot. ciao e grazie

**Comment by xazac** [comment]
Ciao, non trovo gli screenshot!

Inviato da iPhone 6s Plus

**Comment by angelo1976** [comment]
Mi dai il tuo indirizzo email? 



Inviato tramite XiaomiIl Roberto <notifications@github.com>, 01/gen/2016 14:50 ha scritto:Ciao, non trovo gli screenshot!

Inviato da iPhone 6s Plus

**Comment by angelo1976** [comment]
Io ho fatto rispondi da PC 



Inviato tramite XiaomiIl Roberto <notifications@github.com>, 01/gen/2016 14:50 ha scritto:Ciao, non trovo gli screenshot!

Inviato da iPhone 6s Plus

**Comment by xazac** [comment]
Devi allegarli qui

**Comment by angelo1976** [comment]
Ora li vedi? 



Inviato tramite XiaomiIl 01/gen/2016 14:50, Roberto <notifications@github.com> ha scritto:Ciao, non trovo gli screenshot!

Inviato da iPhone 6s Plus

**Comment by xazac** [comment]
No

**Comment by angelo1976** [comment]
io li metto non è che spamma il sistema? Li rimetto. Se no c’è un modo per postarli direttamente sul sito?

**Comment by xazac** [comment]
Segnalalo in questa discussione: http://www.miui.it/forum/index.php?threads/miui-7-segnalazioni-traduzioni-italian-pack.11251/

Grazie!

**Comment by angelo1976** [comment]
Grazie a te 



Inviato tramite XiaomiIl Roberto <notifications@github.com>, 01/gen/2016 19:18 ha scritto:Segnalalo in questa discussione: http://www.miui.it/forum/index.php?threads/miui-7-segnalazioni-traduzioni-italian-pack.11251/

Grazie!

**Comment by ale8530** [comment]
Chiusa
