### ISSUE TITLE
Errore parola

### ISSUE THREAD

**Issue by mello0303** [MishFdM/MIUI_V7_Italy#423]
In imposazioni / display è scritto ”DOPPO tap sullo schermo per attivarlo".

**Comment by xazac** [comment]
Dispositivo? Dovrei averlo già sistemato ma se mi dici che dispositivo hai, controllo!

**Comment by mello0303** [comment]
Mi4c, grazie

**Comment by xazac** [comment]
Risolto, troverai la modifica nelle prossime release. Grazie!

**Comment by ale8530** [comment]
Chiusa per fix inserito da xazac
