### ISSUE TITLE
Errore parola

### ISSUE THREAD

**Issue by mello0303** [MishFdM/MIUI_V7_Italy#424]
Un altro piccolo errore. In sicurezza, dopo aver lanciato la pulizia, nelle azioni da ottimizzare, dopo aver premuto ottimizza, su un azione che riguardava la sicurezza che non ricordo purtoppo bene, il messaggio che compare dopo a schermo inizia con "inseRTO ..." al posto di inserito.

**Comment by mello0303** [comment]
Mi4c

**Comment by mello0303** [comment]
Trovato
Disattivare da impostazioni/applicazioni di sistema / sicurezza "mostra nella barra di notifica"
Poi dalla app sicurezza lanciare una verifica.
Scegliere "ottimizza" all'opzione "controlli pannello di notifica"
Il messaggio a video, in basso che compare è
"Inserto nel pannello di notifica"

**Comment by xazac** [comment]
Risolto, troverai la modifica nelle prossime release! Grazie mille.

**Comment by ale8530** [comment]
Chiusa per fix inserito da xazac
