### ISSUE TITLE
Sicurezza, Pulizia, Pulisci

### ISSUE THREAD

**Issue by Stefano13121970** [MishFdM/MIUI_V7_Italy#426]
Ci sono scritte in Cinese e in Inglese.
Xiaomi Redmi Note 2 Prime

**Comment by ale8530** [comment]
Screenshot grazie

**Comment by Stefano13121970** [comment]
Scusa è la prima che sono qui, come faccio ad allegarlo?

**Comment by Stefano13121970** [comment]
Ok, trovato

**Comment by Stefano13121970** [comment]
![screenshot_2016-01-08-09-56-45_com miui cleanmaster](https://cloud.githubusercontent.com/assets/16607220/12194821/04ccb2be-b5f3-11e5-904f-ac07ec3eb654.png)

**Comment by Stefano13121970** [comment]
Grazie

2016-01-08 10:27 GMT+01:00 ale8530 <notifications@github.com>:

> Screenshot grazie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MishFdM/MIUI_V7_Italy/issues/426#issuecomment-169945304>
> .
>



-- 
*Google Mail*

**Comment by ingbrzy** [comment]
just clean CleanMaster app data...

**Comment by ale8530** [comment]
Ingbirzy dice di pulire il data dell'applicazione CleanMaster e Sicurezza dalle impostazioni

Thanks ingbirzy for this info :)

**Comment by Stefano13121970** [comment]
Grazie ale8530, non riesco scusa! non trovo il percorso

**Comment by Stefano13121970** [comment]
Sorry ... I can not find the path

2016-01-08 10:33 GMT+01:00 ingbrzy <notifications@github.com>:

> just clean CleanMaster app data...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MishFdM/MIUI_V7_Italy/issues/426#issuecomment-169946404>
> .
>



-- 
*Google Mail*

**Comment by ingbrzy** [comment]
Settings - apps - cleanmaster (or cleaner) - clean app data

**Comment by Stefano13121970** [comment]
Ok, fatto! GRAZIE!

**Comment by ale8530** [comment]
Closed.

Thanks ingbrzy
