### ISSUE TITLE
Impostazioni aggiuntive alla seconda voce menù

### ISSUE THREAD

**Issue by Stefano13121970** [MishFdM/MIUI_V7_Italy#427]
Transfer

**Comment by ale8530** [comment]
Non è un bug.

**Comment by Stefano13121970** [comment]
Io non dico che è un bug! dico che non è Italiano!

**Comment by Stefano13121970** [comment]
Pensavo si segnalare parole non tradotte, in modo che nelle prossime versioni ROM... siano scritte in Italiano
