### ISSUE TITLE
Impostazioni aggiuntive alla  seconda voce, stampa

### ISSUE THREAD

**Issue by Stefano131270** [MishFdM/MIUI_V7_Italy#428]
Enable printing

**Comment by ale8530** [comment]
Screenshot grazie

**Comment by Stefano13121970** [comment]
Tra poco, scusa

**Comment by Stefano13121970** [comment]
![screenshot_2016-01-08-09-55-17_com android settings](https://cloud.githubusercontent.com/assets/16607220/12195377/1616bde0-b5f7-11e5-8022-1b15e6723d82.png)

**Comment by ale8530** [comment]
Noi non abbiamo questa funzione che ROM monti?

**Comment by Stefano131270** [comment]
Ciao, scusa ho scritto talmente tante cose che la memoria mi ha tradito.
Volevo segnalare che in Applicazioni di sistema, Email, Confirm before
sending andrebbe tradotto.
Mi scuso per l'errore.
Ciao
Stefano


*Google Mail*


2016-01-21 21:41 GMT+01:00 ale8530 <notifications@github.com>:

**Comment by ale8530** [comment]
Screenshot grazie :)

**Comment by Stefano131270** [comment]
Scusa ale,
ti ricopio quello che ti ho scritto il 22 gennaio

Ciao, scusa ho scritto talmente tante cose che la memoria mi ha tradito.
Volevo segnalare che in Applicazioni di sistema, Email, Confirm before
sending andrebbe tradotto.
Mi scuso per l'errore.
Ciao
Stefano






*Google Mail*


2016-01-26 9:33 GMT+01:00 ale8530 <notifications@github.com>:

**Comment by ale8530** [comment]
Chiusa
