### ISSUE TITLE
errori parole

### ISSUE THREAD

**Issue by mello0303** [MishFdM/MIUI_V7_Italy#429]
Ciao

Ho aggiornato alla 6.1.7 su mi4c, scaricando il zip e aggiornando da updater. Ho verificato se fossero stati corretti gli errori segnalati nei giorni scorsi, ovvero "doPPo tap sullo schermo" e "InseRTo nella barra di notifica", ma li ritrovo ancora.
E' un problema del mio telefono o saranno riportati nella prossima release?
Grazie!

**Comment by ale8530** [comment]
Devi avere la nostra rom. Chiuso bug
