### ISSUE TITLE
titolo non tradotto

### ISSUE THREAD

**Issue by liberato78** [MishFdM/MIUI_V7_Italy#431]
In privacy in impostazioni aggiuntive il titolo del sotto menu advanced non è tradotto.

**Comment by xazac** [comment]
Dovrei averlo già risolto, troverai la modifica nella prossima release. D'ora in avanti, utilizza sempre questo thread per segnalare le traduzioni mancanti e/o gli errori: http://www.miui.it/forum/index.php?threads/miui-7-segnalazioni-bug-traduzione.13290/

Grazie mille.
