### ISSUE TITLE
Redmi Note 3: Blocco setup se seleziono lingua italiana

### ISSUE THREAD

**Issue by patit72** [MishFdM/MIUI_V7_Italy#432]
Se seleziono italiano come lingua l'applicazione che verifica l'account miui si arresta in modo anomalo e non permette di proseguire.
Con lingua inglese non succede

**Comment by ale8530** [comment]
Non abbiamo rilasciato ancora nessuna rom. Chiusa

**Comment by patit72** [comment]
Quindi q

2016-01-11 13:48 GMT+01:00 ale8530 <notifications@github.com>:

**Comment by patit72** [comment]
Quindi  xiaomi.eu_multi_hennessy_6.1.7_v7-5.0 non ha il supporto ufficiale italiano?
