### ISSUE TITLE
Scritta cinese

### ISSUE THREAD

**Issue by mello0303** [MishFdM/MIUI_V7_Italy#440]
Alla creazione di un account gmail nella app mail
![screenshot_2016-01-21-14-39-02_com android email_1453384128425](https://cloud.githubusercontent.com/assets/16482082/12482140/4c7109ac-c04e-11e5-91ca-8431e1cae341.jpg)

**Comment by ale8530** [comment]
Che Rom usi?

**Comment by mello0303** [comment]
6.1.14 mi4c. La rom di xiaomi.eu

**Comment by ale8530** [comment]
Chiusa solo miui.it

**Comment by mello0303** [comment]
Scusa ale8530, ma c'è qualcosa che non mi torna...nel sito miui.it si decanta che tutte le rom italiane comprese la multi sono fatte da miui.it sebbene non aggiornate con le ultime traduzioni. Nel change log di xiaomi.eu quando rilasciano al venerdí è scritto di segnalare i bug di traduzione nell'apposita sezione nazionale, per questo arrivo qua. E cosí fanno anche i colleghi di altre nazionalitá.
Quindi o si stanno sbagliando su xiaomi.eu a linkare questo spazio oppure mi sembra che la tua gestione sia un po prepotente e al di fuori di quello che dovrebbe essere una collaborazione. Non è il primo post che mi chiudi senza oppurtuna verifica o spiegazione e questo non mi pare corretto. 
Segnaleró la cosa anche in xiaomi.eu, perchè è inutile che dicano di segnalare i bug qua quando sono risolti cosí.

**Comment by ale8530** [comment]
Le rom xiaomi.eu usano la nostra traduzione, ma è meno aggiornata della nostra che noi rilasciamo dopo qualche giorno,se si tratta di traduzione purtroppo non posso prenderla in considerazione ;).

Non ho nulla contro di te anzi la collaborazione è ben accetta però devo chiudere certo tipi di segnalazione :).

Se vuoi collaborare fa piacere che usi la nostra ROM :)
