### ISSUE TITLE
Crash Mi Account

### ISSUE THREAD

**Issue by Kamur0** [MishFdM/MIUI_V7_Italy#442]
Ciao,

come da screenshoot ho problemi con il Mi Account, mi è inibito l'accesso, crasha di fisso.
E' un device RedMi Note 2, comprato online, nome del firmware: MIUI 66.77.33.00 (LHMCNCH) Stabile.
L'ho trovato già con Playstore installato e relativa patch multilingua [tra cui italiano].

![screenshot_2016-01-19-16-08-16 1](https://cloud.githubusercontent.com/assets/16866041/12537383/28389ca4-c2be-11e5-833e-f586cb79ee34.png)

Altro problema: non mi permette di usare altro broswer che nn sia l'UC mini per android [https://play.google.com/store/apps/details?id=com.uc.browser.en], nonostante abbia già installato Chrome ed avevo l'app Google. La configurazione "setta come broswer default" la deflaggo ma ritornando nelle opzioni la ritrovo biffata. Questo mi impedisce di cliccare su un link e far interagire un'app [es. Twitter] perché mi apre i link con UC mini.

![12570921_10208050381238889_406494087_n](https://cloud.githubusercontent.com/assets/16866041/12537436/a2192236-c2bf-11e5-9433-7f2509a935b9.jpg)

Potete aiutarmi?

**Comment by ale8530** [comment]
Non è una rom di nostra competenza, avendo la rom dello store non possiamo farci nulla o ti rivolgi a loro,oppure tramite il forum miui.it trovi guide su come togliere questa rom piena di problemi.

PS non sei l'unico che quando acquista ha questo tipo di problemi.

**Comment by Kamur0** [comment]
Capisco, grazie.

Quindi mi consigli quel sito? Sai se è affidabile e ti supporta in caso di problemi?
