### ISSUE TITLE
Errore traduzione in Notifica installazione apk - 6.1.14 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#443]
Quando si installa un apk, la notifica visualizzata indica il percorso errato per disattivare la notifica stessa. L'opzione indicata è stata spostata dal menù Sicurezza a quello Privacy. Il testo potrebbe indicare che la notifica è disattivabile in Impostazioni senza indicare il preciso sottomenu così come avviene nella lingua inglese

![2016-01-20 11 43 40](https://cloud.githubusercontent.com/assets/16007271/12569897/5f73d718-c3d3-11e5-8a1b-ce0acb268d58.png)

![2016-01-20 11 47 26](https://cloud.githubusercontent.com/assets/16007271/12569922/932730aa-c3d3-11e5-9679-dfe0a81e5795.png)

**Comment by ale8530** [comment]
Bug confermato, provvediamo a sistemarlo :).

**Comment by timaniac00** [comment]
Grazie
