### ISSUE TITLE
Mancata traduzione in Sicurezza - Pulizia - 6.1.14 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#444]
In seguito alla pulizia, la finestra di riepilogo appare in inglese

![screenshot_2016-01-26-02-39-06_com miui cleanmaster](https://cloud.githubusercontent.com/assets/16007271/12570260/58ee8b7e-c3d6-11e5-9a00-ee1cc314165b.png)

**Comment by ale8530** [comment]
Questo non è un bug, lo prende dai server cinesi.
