### ISSUE TITLE
Errore di traduzione in Sicurezza - Pulizia - 6.1.14 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#445]
"Cestino" andrebbe sostituito con "spazzatura" o "file inutili"

"Pericoloso" con "Pulisci memoria interna"

![2016-01-26 01 47 40](https://cloud.githubusercontent.com/assets/16007271/12570375/5406b25c-c3d7-11e5-90d4-509b26092c82.png)

![2016-01-26 01 46 55](https://cloud.githubusercontent.com/assets/16007271/12570376/56c4a6ca-c3d7-11e5-9427-796f57d7d948.png)

**Comment by ale8530** [comment]
Vedremo come sistemarli

**Comment by timaniac00** [comment]
Grazie
