### ISSUE TITLE
Errore di traduzione in Temi - 6.1.14 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#446]
Se si clicca su un tema, il titolo è "Temi dettagli" invece di "Dettagli tema"

![2016-01-26 01 59 21](https://cloud.githubusercontent.com/assets/16007271/12570580/16c8aeb6-c3d9-11e5-955c-46820cc9be87.png)

**Comment by ale8530** [comment]
Fisseremo anche questo grazie :)

**Comment by timaniac00** [comment]
Grazie
