### ISSUE TITLE
Traduzione mancante in Impostazioni - Applicazioni di sistema - Email - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#447]
"Confirm before sending" non è tradotto in italiano

![2016-01-26 12 05 41](https://cloud.githubusercontent.com/assets/16007271/12600447/26d1630e-c49a-11e5-8005-12f84baacca1.png)

**Comment by ale8530** [comment]
Fissato prossima release.
