### ISSUE TITLE
Errore di traduzione in Messaggi - Impostazioni avanzate - Gestisci messaggi SIM - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#448]
Il titolo è "Messaggio su SIM" invece di Messaggi su SIM". Anche nella lingua inglese è indicato al plurale

![2016-01-26 12 01 33](https://cloud.githubusercontent.com/assets/16007271/12600531/d95864dc-c49a-11e5-99cb-fe4132cf4710.jpg)

![2016-01-26 12 02 24](https://cloud.githubusercontent.com/assets/16007271/12600549/f424393a-c49a-11e5-898e-022b4d8c45e4.jpg)

**Comment by ale8530** [comment]
Fissato prossima release.
