### ISSUE TITLE
Errore di traduzione in Email - Allegati - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#449]
Il titolo è "Allegato" invece di "Allegati". Anche nella lingua inglese è indicato al plurale

![2016-01-27 01 41 44](https://cloud.githubusercontent.com/assets/16007271/12601264/1198ecd6-c4a0-11e5-97dd-f5ea0212b998.jpg)

![2016-01-27 01 41 00](https://cloud.githubusercontent.com/assets/16007271/12601294/4d365a76-c4a0-11e5-8702-8ba5e825af5f.jpg)

Nel menu "Ordina per" , "Recenti" andrebbe sostituito con "Predefinito" come indicato nel titolo in alto accanto ad Allegato e come avviene se si selezione un altra modalità di ordinamento

![2016-01-27 01 46 59](https://cloud.githubusercontent.com/assets/16007271/12601333/9e8fcd3a-c4a0-11e5-89d0-f64c6f77f6ce.jpg)

**Comment by ale8530** [comment]
Fissato per prossima release.
