### ISSUE TITLE
Traduzione mancante in Email - Impostazioni - Account - Rimuovi account - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#450]
![2016-01-27 01 52 07](https://cloud.githubusercontent.com/assets/16007271/12601416/295ba420-c4a1-11e5-99c8-38b0beea4f63.png)

**Comment by ale8530** [comment]
Questo è collegato ai server miui non si può tradurre.
