### ISSUE TITLE
Traduzione mancante in Registratore - Elenco registrazioni 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#455]
"items" non è tradotto in italiano

![2016-02-10 23 18 57](https://cloud.githubusercontent.com/assets/16007271/12964497/c77f464c-d050-11e5-8a94-99eeabd7ef0b.png)

**Comment by ale8530** [comment]
Fissato per prossima release.
