### ISSUE TITLE
Errore di traduzione in Pop-up - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#456]
Quando un'app viene terminata, "Mostra il riassunto" andrebbe sostituito con "Mostra resoconto" come avviene bella traduzione ufficiale di Google in italiano

![screenshot_2016-02-12-00-32-37_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/16007271/13002487/1d6ec202-d16f-11e5-93dd-b26699c4c46a.png)

![screenshot_2016-01-31-05-23-50_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/16007271/13002515/513cb1e8-d16f-11e5-9093-875f98b21aaa.png)

**Comment by ale8530** [comment]
Qui è di dubbia interpretazione.

Rimane cosi.

**Comment by timaniac00** [comment]
Su Android stock viene tradotto con resoconto
