### ISSUE TITLE
Errore di traduzione in Notifica WiFi - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#457]
Quando si è connessi ad una rete Wifi pubblica appare scritto, nella relativa notifica: "Collegati a xxxx" invece di "Collegato a xxxx"

![screenshot_2016-02-12-19-08-08_com android chrome](https://cloud.githubusercontent.com/assets/16007271/13028459/e9f27174-d26f-11e5-8a8b-4685e1f6e1c4.png)

**Comment by ale8530** [comment]
Fissato prossima release 6.3.31
