### ISSUE TITLE
Errore di traduzione in Notifica chiusura app - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#458]
C'é un errore di traduzione nel messaggio di chiusura forzata di un'app. Quando viene terminata appare scritto "Chiudi forzatamente xxx" invece di "Chiusa forzatamente xxx"

![screenshot_2016-02-15-02-21-08_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/16007271/13037916/012ae4d6-d38b-11e5-8ead-40b6d8ffcdee.png)

**Comment by ale8530** [comment]
Fissato prossima release 6.3.31
