### ISSUE TITLE
Mancata traduzione in Browser - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#459]
Mancata traduzione in Browser quando si seleziona un link: "OpenURL"

![screenshot_2016-02-25-02-36-01_com android browser](https://cloud.githubusercontent.com/assets/16007271/13307394/2d1b75f0-db6b-11e5-97c2-500b4183249b.png)

**Comment by ale8530** [comment]
Fissato prossima release 6.3.31
