### ISSUE TITLE
Errore di traduzione in Browser - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#462]
Nell'applicazione Browser: "Manieni cronologia"

![screenshot_2016-03-04-14-36-45_com android browser](https://cloud.githubusercontent.com/assets/16007271/13528519/beb28538-e216-11e5-8585-4f8dc4db3a5b.png)

**Comment by ale8530** [comment]
Fissato prossima release 6.3.31
