### ISSUE TITLE
Errore di traduzione in File explorer - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#464]
Errore di traduzione in File Explorer - Telefono - Memoria dispositivo - Spazio disponibile: "TLo spazio..."

Dopo "potrebbe differire" manca "da"

![screenshot_2016-03-04-22-12-42_com android fileexplorer](https://cloud.githubusercontent.com/assets/16007271/13540418/9dfb0a96-e256-11e5-8ddf-71b395a177dd.png)

**Comment by ale8530** [comment]
Fissato prossima release 6.3.31
