### ISSUE TITLE
Mancata traduzione in Impostazioni - Applicazioni di sistema - Musica - 6.3.3 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#465]
![screenshot_2016-03-07-23-24-42_com miui player](https://cloud.githubusercontent.com/assets/16007271/13586654/8cb5f732-e4c2-11e5-9da5-119d98cbb7f8.png)

**Comment by ale8530** [comment]
Già fissato chiuso.
