### ISSUE TITLE
Errore di traduzione in Sicurezza - Utilizzo dati - Impostazioni - 6.3.10 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#466]
C'è un errore di traduzione in Sicurezza - Utilizzo dati - Impostazioni. Sopra "Soglia dati rete mobile" viene indicata erroneamente "WI-FI" nonostante il limite si riferisca alla rete dati cellulare. Nella lingua inglese è infatti indicato con "WIRELESS PLAN"

![2016-03-13 17 52 00](https://cloud.githubusercontent.com/assets/16007271/13730379/a374388c-e94d-11e5-8e95-14e014390755.png)
![screenshot_2016-03-13-18-52-00_com miui networkassistant](https://cloud.githubusercontent.com/assets/16007271/13730380/a4eeac60-e94d-11e5-83db-aae42cca06b9.png)

**Comment by ale8530** [comment]
Fissato prossima release 6.3.31
