### ISSUE TITLE
Blackist app e-mail errata traduzione (cancro 6.3.24)

### ISSUE THREAD

**Issue by minus1988** [MishFdM/MIUI_V7_Italy#469]
ciao...c'è un'errata traduzione nell'app email nel mettere in blacklist le mail di un contatto
![screenshot_2016-03-29-01-10-57_com android email](https://cloud.githubusercontent.com/assets/17927013/14093169/34d917fc-f54c-11e5-8f1e-fb67fd964fc8.png)

**Comment by ale8530** [comment]
Fissato per la release di questa settimana
