### ISSUE TITLE
Errata traduzione quando contatto ha la rete occupata (6.3.24 cancro)

### ISSUE THREAD

**Issue by minus1988** [MishFdM/MIUI_V7_Italy#470]
Come da titolo manca lo spazio nella traduzione "linea occupata"
![screenshot_2016-03-27-19-07-52_com android incallui_1459411352670](https://cloud.githubusercontent.com/assets/17927013/14169441/0903bfdc-f728-11e5-80ee-3ebe7000b0bc.jpg)

**Comment by ale8530** [comment]
miui.it anche se ancora non è supportato cancro è stato fissato in questa release xiaomi.eu dalla prossima.
