### ISSUE TITLE
Errata traduzione impostazioni batteria--gestisci il consumo app (6.3.24 cancro)

### ISSUE THREAD

**Issue by minus1988** [MishFdM/MIUI_V7_Italy#471]
Come da titolo ci sono diverse traduzioni errate nel menù batteria-- gestisci consumo app
![screenshot_2016-03-31-10-07-34_com miui powerkeeper_1459411835717](https://cloud.githubusercontent.com/assets/17927013/14169613/15ffa376-f729-11e5-8aa4-564d472f249f.jpg)

**Comment by ale8530** [comment]
miui.it anche se ancora non è supportato cancro è stato fissato in questa release xiaomi.eu dalla prossima.
