### ISSUE TITLE
Errore di traduzione in Sicurezza - Impostazioni utilizzo dati - 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#473]
"Limita utilizza dati soglia" andrebbe corretto magari eliminando soglia

in "Esegui un test dellaconnessione internet" manca uno spazio

![catturad](https://cloud.githubusercontent.com/assets/16007271/14268355/5e412966-fada-11e5-9402-8521ce7cf3a7.PNG)

**Comment by ale8530** [comment]
Fissato per prossima release
