### ISSUE TITLE
Mancata traduzione in Sicurezza - Impostazioni utilizzo dati - Test di rete -  6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#474]
"Connection" non è tradotto in italiano
![cattura12](https://cloud.githubusercontent.com/assets/16007271/14268446/4e747a64-fadb-11e5-81f5-96869e89acae.PNG)

Cliccando su "Connection" il menù non è tradotto
![cattura13](https://cloud.githubusercontent.com/assets/16007271/14268454/760e7642-fadb-11e5-87e0-2929373e6ba9.PNG)

**Comment by ale8530** [comment]
Fissato per prossima release.
