### ISSUE TITLE
Errore di traduzione in Sicurezza - Impostazioni utilizzo dati - Limita utilizzo dati - 6.3.31 (hennessy) 

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#475]
"Installata" andrebbe sostituita col plurale oppure con "Scaricate" come avviene in Impostazioni - Applicazioni 

"Sistema" con "Di sistema" o "Preinstallate"

"WLAN" con "WiFi"
![cattura55](https://cloud.githubusercontent.com/assets/16007271/14268527/38187e22-fadc-11e5-8dcd-4610d4d73525.PNG)

Cliccando sull'icona delle impostazioni in alto:

"WLAN" con "WiFi"
![cattura88](https://cloud.githubusercontent.com/assets/16007271/14268555/8bc2337e-fadc-11e5-8e32-df62db644e6a.PNG)

**Comment by ale8530** [comment]
Fissato per prossima release.
