### ISSUE TITLE
Errore di traduzione in File explorer - Telefono - Memoria 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#476]
"Lo spazio disponibile mostrato potrebbe differire **da** quello visualizzato dal sistema."  manca "da"

![cattura6666](https://cloud.githubusercontent.com/assets/16007271/14268651/bce9e6a8-fadd-11e5-91df-6b7f8510b9f9.PNG)

**Comment by ale8530** [comment]
Fissato per prossima release
