### ISSUE TITLE
Mancata traduzione in Radio - Lista registrazioni - 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#477]
Cliccando sulla cartella in alto a destra:

"items" non è tradotto

![cattura555](https://cloud.githubusercontent.com/assets/16007271/14268733/a610e386-fade-11e5-8af4-eb3781b445f8.PNG)

**Comment by ale8530** [comment]
Fissato per prossima release
