### ISSUE TITLE
Mancata traduzione in Impostazioni - Impostazioni aggiuntive - Tasti - 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#478]
Il menù "Automatically disable navigation buttons" non è tradotto

![cattura6666666](https://cloud.githubusercontent.com/assets/16007271/14268839/7e463de6-fadf-11e5-83f1-2c096fe6b0a2.PNG)
![cattura858585](https://cloud.githubusercontent.com/assets/16007271/14268856/99a6b46c-fadf-11e5-93ee-f0029161e74e.PNG)

**Comment by ale8530** [comment]
Fissato chiuso
