### ISSUE TITLE
Niente Tastiera (hermes)

### ISSUE THREAD

**Issue by Jambu92** [MishFdM/MIUI_V7_Italy#480]
Ragazzi ho appena comprato un Redmi Note 2, scaricata la rom 6.3.31 weekly ma non mi compare in nessun modo la tastiera, e non so come fare. Consigli?

**Comment by timaniac00** [comment]
dovresti scrivere sul forum http://www.miui.it/forum/index.php

**Comment by ale8530** [comment]
chiusa
