### ISSUE TITLE
Mancata traduzione in File Explorer - Recenti 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#497]
"Pictures" e "Movies" non sono tradotti
 
![screenshot_2016-04-08-11-52-54_com android fileexplorer](https://cloud.githubusercontent.com/assets/16007271/14380704/3ec0e898-fd81-11e5-9417-f631f032a934.png)

**Comment by ale8530** [comment]
Credo non vadano tradotti non trovo stringhe

**Comment by ale8530** [comment]
Non riscontro bug quindi fissato.
