### ISSUE TITLE
Mancata traduzione in Impostazioni - Applicazioni di sistema - Video - 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#498]
![screenshot_2016-04-09-14-42-56_com miui video](https://cloud.githubusercontent.com/assets/16007271/14403697/d27c592e-fe61-11e5-8e98-9f7d724b4759.png)

**Comment by ale8530** [comment]
Fissato prossima release.
