### ISSUE TITLE
Errore di traduzione in Impostazioni - Applicazioni di sistema - Galleria - 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#499]
![screenshot_2016-04-09-14-47-31_com miui gallery](https://cloud.githubusercontent.com/assets/16007271/14403718/6d6b4e4a-fe62-11e5-847c-b8a928ddc2e5.png)

**Comment by ale8530** [comment]
Fissato prossima release.
