### ISSUE TITLE
Errore di traduzione in Impostazioni - Impostazioni aggiuntive - Opzioni sviluppatore - 6.3.31 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#500]
![screenshot_2016-04-09-14-54-08_com android settings](https://cloud.githubusercontent.com/assets/16007271/14403746/5886df0c-fe63-11e5-9456-1c7602cfc2c0.png)

**Comment by ale8530** [comment]
chiusa, è un problema di spazio!
