### ISSUE TITLE
Problema con la traduzione in Impostazioni > Memoria (hermes)

### ISSUE THREAD

**Issue by tonyado** [MishFdM/MIUI_V7_Italy#501]
Errore di traduzione nella sezione Scheda SD nominata come archivio USB

![image](https://cloud.githubusercontent.com/assets/18469966/14542336/c61d243e-028e-11e6-8bbb-4fa9f24942e0.png)
![image](https://cloud.githubusercontent.com/assets/18469966/14542354/d90d9e0c-028e-11e6-92d2-0f8ac6fd9565.png)

**Comment by ale8530** [comment]
Fix [https://github.com/MishFdM/MIUI_V7_Italy/commit/2f7a7651f925d8937febb0c38c1b1f93bbbb1646](url)
