### ISSUE TITLE
Errore di traduzione redmi3 (ido)

### ISSUE THREAD

**Issue by motorgia** [MishFdM/MIUI_V7_Italy#503]
Errore di traduzione in impostazioni/impostazioni avanzate/uso cona mano

**Comment by ale8530** [comment]
già fissato

**Comment by motorgia** [comment]
Invece l'errore c'è ancora "uso cona mano"
Il 01/mag/2016 06:55 PM, "ale8530" <notifications@github.com> ha scritto:

**Comment by ale8530** [comment]
è stato approvato oggi, arriverà prossima release.

**Comment by motorgia** [comment]
Ok grazie per l' informazione. A proposito sai se la prossima release
supporterà nuovamente il redmi3?
Il 01/mag/2016 07:47 PM, "ale8530" <notifications@github.com> ha scritto:
