### ISSUE TITLE
Mancata traduzione in Notifica - 6.4.21 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#505]
![screenshot_2016-04-30-18-45-12_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/16007271/14941893/d03a77f2-0fac-11e6-9c5a-48e12b074297.png)
![screenshot_2016-04-30-18-45-40_com android phone](https://cloud.githubusercontent.com/assets/16007271/14941896/f17c1b96-0fac-11e6-8f98-424968d6baa3.png)

**Comment by ale8530** [comment]
Fissato
