### ISSUE TITLE
Errore di traduzione in Sicurezza - Verifica - Sistema - 6.4.28 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#513]
Nella lingua inglese non è presente  io numero di virus rilevati ma una descrizione del comando 
![screenshot_2016-05-03-01-26-34_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/14971088/1019556e-10cf-11e6-9998-02c53fbe1db8.png)

![screenshot_2016-05-03-01-27-35_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/14971077/f5819da6-10ce-11e6-9fe5-bc1c78aeab9c.png)

**Comment by ale8530** [comment]
Fissato
