### ISSUE TITLE
Errore di traduzione in Sicurezza - Pulizia - 6.4.28 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#514]
"Cestino" andrebbe sostituito con "spazzatura"

![screenshot_2016-05-03-01-38-37_com miui cleanmaster](https://cloud.githubusercontent.com/assets/16007271/14971153/f747e0ea-10cf-11e6-9f47-7b32028d5f45.png)
![screenshot_2016-05-03-01-37-00_com miui cleanmaster](https://cloud.githubusercontent.com/assets/16007271/14971161/0a9284f2-10d0-11e6-9a19-a803a4e3070f.png)

**Comment by ale8530** [comment]
Fissato
