### ISSUE TITLE
Mancata traduzione in Pannello delle notifiche - Tasti - 6.4.28 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#515]
Cliccando su Tasti appaiono due notifiche inglese 
![screenshot_2016-05-03-01-52-40_com android chrome](https://cloud.githubusercontent.com/assets/16007271/14971364/c32e9446-10d1-11e6-992d-7ec8bd7ff8df.png)
![screenshot_2016-05-03-01-52-36_com android chrome](https://cloud.githubusercontent.com/assets/16007271/14971367/c9b3f482-10d1-11e6-9e63-310457b69b52.png)

**Comment by ale8530** [comment]
Fissato prossima per release.
