### ISSUE TITLE
Errore di traduzione in Pannello delle notifiche - Mi Drop - 6.4.28 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#516]
"Condividi file **coni** dispositivi..."
![screenshot_2016-05-03-01-54-16_com xiaomi midrop](https://cloud.githubusercontent.com/assets/16007271/14971405/3621f6be-10d2-11e6-82ad-b2d4c6f4822b.png)

**Comment by ale8530** [comment]
Fissato
