### ISSUE TITLE
Mancata traduzione notifica - 6.4.28 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#520]
![screenshot_2016-05-04-01-55-03_com android chrome](https://cloud.githubusercontent.com/assets/16007271/15001859/724849bc-119b-11e6-90fd-4bdda2bd4e54.png)

**Comment by ale8530** [comment]
Dovrei averlo fissato per prossima release.

Se ci sono problemi commentami in questa pagina per ora chiudo.
