### ISSUE TITLE
Mancata traduzione in Notifica - Testa rete - 6.4.28 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#525]
![screenshot_2016-05-07-14-44-17_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/15092469/8e51b422-146b-11e6-9840-d0319c5f7c1e.png)

**Comment by enricocid** [comment]
con i cambiamenti che ho fatto in securitycenter

https://github.com/MishFdM/MIUI_V7_Italy/pull/527

credo di aver coperto questa issue

**Comment by ale8530** [comment]
Chiusa
