### ISSUE TITLE
Mancata traduzione in Notifica - 6.4.28 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#526]
![screenshot_2016-05-07-09-39-20_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/15092495/f046dfa4-146b-11e6-8934-cf1deb4b49ed.png)

**Comment by enricocid** [comment]
con i cambiamenti che ho fatto in securitycenter

https://github.com/MishFdM/MIUI_V7_Italy/pull/527

credo di aver coperto questa issue

**Comment by ale8530** [comment]
Chiusa
