### ISSUE TITLE
Errore di traduzione in Sicurezza - Verifica - Sistema - 6.5.5 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#528]
"Rimuovi i virus per mantenere il dispositivo" manca "sicuro"

"Auto aggiornamento **definizione** virus attivato" andrebbe corretto in "definizioni"

"Puliti" potrebbe essere sostituito con "Protezioni", "Elementi di protezione"

![screenshot_2016-05-09-11-45-54_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/15109565/430a68c0-15dc-11e6-823f-b3b3cf68ea69.png)
![screenshot_2016-05-09-11-47-03_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/15109567/446f76ce-15dc-11e6-9dbe-ef48212f416b.png)

**Comment by ale8530** [comment]
Escluso puliti che rimane cosi è stato fissato tutto.
