### ISSUE TITLE
Errore di traduzione in Sicurezza - Limita utilizzo dati - 6.5.5 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#532]
"Installata" andrebbe sostituita con "Scaricate"

"Sistema" con "Di sistema"

"WLAN" con "Wi-Fi"

![screenshot_2016-05-13-14-48-39_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/15248457/9d16e082-191a-11e6-8a0e-3c6c2ab0d578.png)

![screenshot_2016-05-13-14-48-53_com miui securitycenter](https://cloud.githubusercontent.com/assets/16007271/15248510/e41fceda-191a-11e6-9d6f-cca73382051c.png)

**Comment by xazac** [comment]
Risolto!
