### ISSUE TITLE
Errore di traduzione su Redmi Note 2 Hermes 6.5.19

### ISSUE THREAD

**Issue by VILLO1988** [MishFdM/MIUI_V7_Italy#537]
Spero di postare nel luogo corretto.

La traduzione in Impostazioni>Impostazioni Avanzate>Gestisci il consumo da parte delle app>Scegli Applicazioni > è  App Instalalte.

![screenshot_2016-05-21-11-57-37_com miui powerkeeper](https://cloud.githubusercontent.com/assets/19503753/15447959/bb743c58-1f52-11e6-96ef-1f6dc11dd3a3.png)

**Comment by VILLO1988** [comment]
Ho recentemente scoperto inoltre che cliccando su un applicazione si hanno le classiche 2 opzioni per limitare i consumi, di cui la terza riga è:
-LImita attività in Background (i è maiuscola)
Le app verranno chiuse per risprmiare batteria (manca una a)

**Comment by ale8530** [comment]
Tu utilizzi rom xiaomi.eu? mi sembra di averti visto li.
