### ISSUE TITLE
Mancata traduzione in Impostazioni - Impostazioni aggiuntive - Tasti -  6.5.12 (hennessy) 

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#538]
![screenshot_2016-05-22-21-38-11_com android settings](https://cloud.githubusercontent.com/assets/16007271/15456066/bdd5110c-2065-11e6-945a-434775fef8dc.png)

![screenshot_2016-05-22-21-41-38_com android settings](https://cloud.githubusercontent.com/assets/16007271/15456077/012913a4-2066-11e6-8559-67a7ad3be462.png)

**Comment by ale8530** [comment]
che versione monti? mi sembra già di averti fissato questo bug.

**Comment by ale8530** [comment]
installa la 6.5.19 e fammi sapere se hai ancora lo stesso bug.

**Comment by ale8530** [comment]
Ne riparliamo alla v8 per i bug traduzione ;)

Chiusa
