### ISSUE TITLE
Mancata traduzione in Download - 6.5.12 (hennessy)

### ISSUE THREAD

**Issue by timaniac00** [MishFdM/MIUI_V7_Italy#539]
![screenshot_2016-05-23-10-05-54_com android providers downloads ui](https://cloud.githubusercontent.com/assets/16007271/15464234/4fca38ea-20ce-11e6-84fd-6b4452cb15b3.png)

![screenshot_2016-05-23-10-06-26_com android providers downloads ui](https://cloud.githubusercontent.com/assets/16007271/15464236/5389d8aa-20ce-11e6-98a2-1360c3008b9c.png)

![screenshot_2016-05-23-10-06-51_com android providers downloads ui](https://cloud.githubusercontent.com/assets/16007271/15464238/563bc072-20ce-11e6-8f92-866659885243.png)

**Comment by ale8530** [comment]
installa la 6.5.19 e fammi sapere se hai ancora lo stesso bug.

**Comment by timaniac00** [comment]
Risolto, grazie
