### ISSUE TITLE
issue in download 

### ISSUE THREAD

**Issue by vincenzone** [MishFdM/MIUI_V7_Italy#541]
buongiorno,
miui 7.4 by xiaomi.eu 6.5.19 su download impostazioni non si riesce a settare il limite di download ma appare una schermata con scritto informazioni versione 6.03.11.700002
grazie
![image](https://cloud.githubusercontent.com/assets/19589047/15571874/bda6f2ec-233d-11e6-81bc-87165ac929ec.png)

**Comment by ale8530** [comment]
Devi segnalare a loro non a noi.
